// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('bootstrap/dist/js/umd/util.js')
require('bootstrap/dist/js/umd/alert.js')
require('bootstrap/dist/js/umd/button.js')
require('bootstrap/dist/js/umd/carousel.js')
require('bootstrap/dist/js/umd/collapse.js')
require('bootstrap/dist/js/umd/dropdown.js')
require('bootstrap/dist/js/umd/modal.js')
require('bootstrap/dist/js/umd/scrollspy.js')
require('bootstrap/dist/js/umd/tab.js')
require('bootstrap/dist/js/umd/tooltip.js')
require('bootstrap/dist/js/umd/popover.js')

